authors/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('register/', views.register_view, name='register'),
]

projeto/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipes.urls')),
    path('authors/', include('authors.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

recipes/urls.py
from django.urls import path
from . import views

app_name = 'recipes'

urlpatterns = [

    path('', views.home , name= "home"),
    path('recipes/search/', views.search, name="search"),
    path('recipes/category/<int:category_id>/', views.category, name="category"),
    path('recipes/<int:id>/', views.recipe, name="recipe"),
]

authors/models.py
from django.db import models

# Create your models here.

recipes/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=65)

    def __str__(self):
        return self.name

class Recipe(models.Model):

    title = models.CharField(max_length=65)
    description = models.CharField(max_length=65)
    slug = models.SlugField(unique= True)
    preparation_time = models.IntegerField()
    preparation_time_unit = models.CharField(max_length=65)
    servings = models.IntegerField()
    servings_unit = models.CharField(max_length=65)
    preparation_steps = models.TextField()
    preparation_steps_is_html = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_published = models.BooleanField(default=False)
    cover = models.ImageField(upload_to='recipes/covers/%Y/%m/%d/', blank=True, default='')
    category = models.ForeignKey(Category, on_delete=models.SET_NULL , null= True)
    author = models.ForeignKey(User, on_delete= models.SET_NULL, null = True )

    def __str__(self):
        return self.title
    

authors/forms.py
from django import forms
from django.contrib.auth.models import User


class RegisterForm(forms.ModelForm):
    class Meta:
        model = User
        fields = [
            'first_name',
            'last_name',
            'username',
            'email',
            'password',
        ]

authors/views.py
from django.shortcuts import render

from authors.forms import RegisterForm

def register_view(request):
    if request.POST:
        form = RegisterForm(request.POST)
    else:
        form = RegisterForm()
    return render(request, 'authors/register_view.html', {
        'form': form,
    })

recipes/views.py
from django.http import Http404
from django.shortcuts import get_list_or_404, render
from recipes.models import Recipe
from django.db.models import Q

def home(request):
    recipes = Recipe.objects.filter(is_published = True).order_by('-id')
    return render(request, 'recipes/pages/home.html', context={
        'recipes': recipes,
    })

def category(request, category_id):
    recipes = get_list_or_404(Recipe.objects.filter(category__id = category_id, is_published = True ).order_by('-id'))

    return render(request, 'recipes/pages/category.html', context={
        'recipes': recipes,
        'title': recipes[0].category.name
    })

def recipe(request, id):
    recipe = Recipe.objects.filter(pk=id,is_published = True).first()

    return render(request, 'recipes/pages/recipe-view.html', context={
        'recipe': recipe,
        'title' : recipe.title,
        'is_page_details': True,
    })

def search(request):
    search_term = request.GET.get('q', '').strip()

    recipes = Recipe.objects.filter(Q(title__icontains=search_term) | 
        Q(description__icontains=search_term), is_published=True).order_by('-id')
   

    if not search_term:
        raise Http404()
    return render(request, 'recipes/pages/search.html',
                  context= {'title_page' : search_term,
                            'recipes' : recipes})

authors/templates/authors/register_view.html
{% extends 'global/base.html' %}

{% block title %}Register | {% endblock title %}

{% block content %}
  <div class="main-content center container">
    <h2>Register</h2>
  </div>

  <div class="main-content container">
    <form action="" method="POST">
      {% csrf_token %}

      <div class="form-content form-content-grid">
        {% for field in form %}
          <div class="form-group">
            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
            {{field}}

            {% if field.help_text %}
              <p class="help-text">{{ field.help_text }}</p>
            {% endif %}

            {{ field.errors }}
          </div>
        {% endfor %}
      </div>

      <div class="form-group">
        <button type="submit">Send</button>
      </div>
    </form>
  </div>
{% endblock content %}

recipes/templates/recipes/pages/category.html
{% extends 'global/base.html' %}

{% block title %}{{title}} | {% endblock title %}

{% block content %}
<div class="main-content main-content-list container">

    
    {% for recipe in recipes %}
        {% include 'recipes/partials/recipe.html' %}
    {% endfor %}
</div>
{% endblock content %}

recipes/templates/recipes/pages/home.html
{% extends 'global/base.html' %}

{% block title %}Home | {% endblock title %}

{% block content %}
<div class="main-content main-content-list container">

    {% for recipe in recipes %}
        {% include 'recipes/partials/recipe.html' %}
    {% empty %}
        <h1>No found recipes. </h1>
    {% endfor %}
    
    {% for recipe in recipes %}
        {% include 'recipes/partials/recipe.html' %}
    {% endfor %}
</div>
{% endblock content %}

recipes/templates/recipes/pages/recipe-view.html
{% extends 'global/base.html' %}

{% block title %}{{title}}| {% endblock title %}

{% block content %}
    <div class="main-content main-content-detail container">
        {% include 'recipes/partials/recipe.html' %}
    </div>
{% endblock content %}

recipes/templates/recipes/pages/search.html
{% extends 'global/base.html' %}

{% block title %}search for {{title_page}}| {% endblock title %}

{% block content %}
<div class="main-content main-content-list container">

    {% for recipe in recipes %}
        {% include 'recipes/partials/recipe.html' %}
    {% empty %}
        <h1>No found recipes. </h1>
    {% endfor %}
    
    {% for recipe in recipes %}
        {% include 'recipes/partials/recipe.html' %}
    {% endfor %}
</div>
{% endblock content %}

recipes/templates/recipes/partials/footer.html
<footer class="main-footer">
    <div class="developer">
      <a href="https://www.linkedin.com/in/maria-jordana-cavalcante-233237252/" target="_blank" rel="noreferrer noopener">By Jordana Cavalcante</a>
    </div>
  
    <div class="powered">
      <a href="https://www.djangoproject.com/" target="_blank" rel="noreferrer noopener">Powered by Django</a>
    </div>
  </footer>

recipes/templates/recipes/partials/head.html
{% load static %}
<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/fontawesome.min.css"
    integrity="sha512-P9vJUXK+LyvAzj8otTOKzdfF1F3UYVl13+F8Fof8/2QNb8Twd6Vb+VD52I7+87tex9UXxnzPgWA3rH96RExA7A=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/brands.min.css"
    integrity="sha512-sVSECYdnRMezwuq5uAjKQJEcu2wybeAPjU4VJQ9pCRcCY4pIpIw4YMHIOQ0CypfwHRvdSPbH++dA3O4Hihm/LQ=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/solid.min.css"
    integrity="sha512-tk4nGrLxft4l30r9ETuejLU0a3d7LwMzj0eXjzc16JQj+5U1IeVoCuGLObRDc3+eQMUcEQY1RIDPGvuA7SNQ2w=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />

<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@900&display=swap" rel="stylesheet">
<link rel="stylesheet" href="{% static 'recipes/css/style.css' %}">
<link rel="stylesheet" href="{% static 'global/css/global-style.css' %}">

recipes/templates/recipes/partials/header.html
<header class="main-header-container">
    <div class="main-header container">
        <h1>
            <a class="main-logo" href="{% url 'recipes:home' %}">
                <i class="fas fa-utensils main-logo-icon"></i>
                <span class="main-logo-text">Recipes</span>
            </a>
        </h1>
    </div>
</header>

recipes/templates/recipes/partials/recipe.html
<div class="recipe recipe-list-item">
    <div class="recipe-cover">
        {% if recipe.cover %}
        <div class="recipe-cover">
            <a href="{% url 'recipes:recipe' recipe.id %}">
                <img src="{{ recipe.cover.url }}" alt="Temporário">
            </a>
        </div>
    {% endif %}
    </div>
    <div class="recipe-title-container">
        <a href = "{% url 'recipes:recipe' recipe.id %}">
            <h2 class="recipe-title">{{ recipe.title }}</h2>
        </a>
    </div>

    <div class="recipe-author">
        <span class="recipe-author-item">
            <i class="fas fa-user"></i>

            {% if recipe.author is not None %}
                {% if recipe.author.first_name %}
                    {{ recipe.author.first_name }} {{ recipe.author.last_name }}
                {% else %}
                    {{recipe.author.username}}
                {% endif %}
            {% else %}
                desconhecido
            {% endif %}
                             
        </span>
        <span class="recipe-author-item">
            <i class="fas fa-calendar-alt"></i>
            {{ recipe.created_at|date:"d/m/Y" }} às {{ recipe.created_at|date:"H:i" }}
        </span>
        <span class="recipe-author-item">
            <a href="{% url 'recipes:category' recipe.category.id %}">
                <i class="fas fa-layer-group"></i>
                <span>{{ recipe.category.name }}</span>
            </a>
        </span>
    </div>

    <div class="recipe-content">
        <p>{{ recipe.description }}</p>
    </div>

    <div class="recipe-meta-container">
        <div class="recipe-meta recipe-preparation">
            <h3 class="recipe-meta-title"><i class="fas fa-stopwatch"></i> Preparo</h3>
            <div class="recipe-meta-text">
                {{ recipe.preparation_time }} {{ recipe.preparation_time_unit }}
            </div>
        </div>
        <div class="recipe-meta recipe-servings">
            <h3 class="recipe-meta-title"><i class="fas fa-pizza-slice"></i> Porções</h3>
            <div class="recipe-meta-text">
                {{ recipe.servings }} {{ recipe.servings_unit }}
            </div>
        </div>
    </div>

    {% if is_page_details is not True%}
        <footer class="recipe-footer">
            <a class="recipe-read-more button button-dark button-full-width" href="{% url 'recipes:recipe' recipe.id %}">
                <i class="fas fa-eye"></i>
                <span>ver mais...</span>
            </a>
        </footer>
    {% endif %}

    {% if is_page_details is True %}
        <div class="preparation-steps">
            {{recipe.preparation_steps | linenumbers | linebreaksbr}}
        </div>
    {% endif %}
</div>

recipes/templates/recipes/partials/search.html
<div class="search-container">
    <div class="container">
        <form action="{% url 'recipes:search' %}" method="GET"  class="search-form">
            <input type="search" class="search-input" name="q" value="{{search_term}}"required>
            <button type="submit" class="search-button"><i class="fas fa-search"></i></button>
        </form>
    </div>
</div>